---
title: "Proyecto Final"
author: "Erick Zarza, Edmar Trapaga."
date: "11 de mayo de 2018"
output:
  html_document: 
    df_print: paged 
    theme: cerulean
    code_folding: hide
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F, 
                      error = F,fig.align = "center",
                      fig.height = 5, fig.width = 5,
                      fig.path='figure/', cache=F,
                      cache.path='cache/')
```

```{r directory_libraries_seed}
setwd("C:/Users/EZ/Desktop/ITAM/E-E/Actuarial III")

libraries <- c("tidyverse","kableExtra", "grid", "knitr", "gridExtra", "readxl", "latex2exp")

invisible(lapply(libraries, library,
                 character.only = TRUE)) #carga todos los paquete requeridos sin imprimir el resultado de hacerlo

set.seed(139380)
```

# {.tabset .tabset-fade .tabset-pills} 

1.1 Modelo Colectivo

```{r, cache=F}
# f_n <- función de masa de probabilidad de la frecuencia 
sop <- seq(0,100000,1000)
lambda <- 0.1 # =E[N]= media de la frecuencia
n <- 0:5 # # soporte de la frecuencia
theta <- 10000 # =E[X]= media de la severidad


f_n <- matrix(nrow=2,ncol=length(n)) %>% as.data.frame()
for (i in 0:(length(n)-1)){
  f_n[,i+1] <- c(n[i+1],dpois(n[i+1],lambda)) 
}

colnames(f_n) <- c(paste0("Pr(N=",n,")"))
rownames(f_n) <- c("n","Pr(N=n)")

# F_nx <- distribución de la n-ésima convolusión

F_n <- function(n){ifelse(n==0,1,0)}

F_nx <- matrix(nrow=length(sop),ncol=length(n)) %>% as.data.frame()

for (i in 0:(length(n)-1)){
  F_nx[,i+1] <- c(F_n(n[i+1]),
            ifelse(n[i+1]==0,0,1)*pgamma(
              sop[-1],shape=n[i+1],scale=theta)) 
}

F_nx[,1] <- format(F_nx[,1], scientific = F) %>% as.numeric()
F_nx[1,] <- format(F_nx[1,], scientific = F) %>% as.numeric()

colnames(F_nx) <- c(paste0("",n,""))
rownames(F_nx) <- c(paste0("",format(sop, scientific = F),""))



# F_s distribución acumulada del modelo agregado

F_s <- NULL

F_s[1] <- sum(f_n[2,]*F_nx[1,])

for (i in 1:(length(sop))-1){
F_s[1] <- sum(f_n[2,]*F_nx[1,])
F_s[i+1] <- F_s[1] + sum(f_n[2,]*F_nx[i+1,])
}

# f_s densidad de probabilidad del modelo agregado

f_s <- NULL
f_s[1] <- F_s[1]
for(i in 1:(length(sop)-1)){
f_s[i+1] <- F_s[i+1]-F_s[i]
}

#tabla completa para modelo agregado

mod_agregado <- data.frame(s=format(sop, 
                                      scientific = F) %>% as.numeric(),
                           fs=f_s,Fs=F_s)
names(mod_agregado) <- c("s","f(s)","F(s)")
```

```{r}
kable(f_n, format.args = list(big.mark= ","))
kable(F_nx,format.args = list(big.mark = ","))
kable(mod_agregado,format.args = list(big.mark = ","))
```

```{r}
ggplot(mod_agregado,aes(x=s,y=`f(s)`)) + geom_point() + theme_bw()
ggplot(mod_agregado,aes(x=s,y=`F(s)`)) + geom_point() + theme_bw()

```

1.2

```{r}
n_sim <- 10000
#lambda <- 0.1
#theta <- 10000
sim_i <- NULL
N_cuenta <- NULL

for(i in 1:n_sim){
N <- rpois(1,lambda = lambda)
X_i <- rexp(N,1/theta)
S_i <- sum(X_i)
sim_i[i] <- S_i 
N_cuenta[i] <- N
}

#Data frame de las simulaciones y gráfica de dist empírica
sim_i <- data.frame(sim_i) 
colnames(sim_i) <- "sim"

ggplot(sim_i, aes(sim)) + stat_ecdf(geom = "step") + coord_cartesian(ylim=(c(.9,1)),xlim=c(0,100000)) + theme_bw()

#s <- mod_agregado$s %>% as.character() %>% as.numeric()
#f_s <- mod_agregado$`f(s)` %>% as.character() %>% as.numeric()

s <- mod_agregado$s 
f_s <- mod_agregado$`f(s)` 
```

#Gama trasladada

```{r}
theta <- 1/10000
E_X <- 1/theta #Media de severidad
E_X2 <- 2/(theta^2) #Segundo momento severidad
E_X3 <- 6/(theta^3) #TErcer momento severidad

alpha <- 4*lambda*(E_X2)^3/(E_X3)^2 # parámetro alpha para proximacion gama
beta <- 2*(E_X2/E_X3) # parámetro beta de aproximacion gama
x_0 <-lambda*E_X-(2*lambda*(E_X2)^2)/E_X3 # parámetro de traslación para aproximación gama

media_s <- sum(s*f_s)
mediasim_s <- sim_i$sim %>% mean()

E_S <- x_0+(alpha/beta)
E_S  # Media de Gama
mediasim_s # Media de simulaciones
media_s # Media de conv
```

# Varianza

```{r}
var_gama_s <- alpha/beta^2 #
var_sim_s <- var(sim_i$sim)

E_X2_convoluciones <- sum(s^2*f_s) #Segundo momento de la distribución de convoluciones
var_s <- E_X2_convoluciones-(media_s)^2 #Varianza de convoluciones

c(var_gama_s,sqrt(var_gama_s)) # Varianza de gama trasaladada
c(var_sim_s,sqrt(var_sim_s)) # Varianza de simulaciones
c(var_s,sqrt(var_s)) # Varianza de las convoluciones
```

# Sesgo

```{r}
sesgo_gama_s <- 2*alpha/beta^3 #sesgo(skewness)
sesgo_s <- sum((s-media_s)^3*f_s) #sesgo(skewness) convoluciones
c(sesgo_gama_s,sesgo_s)

coef_sesgo_gama_s <- sesgo_gama_s/(var_gama_s)^(3/2) #coeficiente de sesgo gama
coef_sesgo_s <- sesgo_s/(var_s)^(3/2) #coeficiente de sesgo convoluciones
c(coef_sesgo_gama_s,coef_sesgo_s)
```

# Kurtosis

```{r}
kurtosis_s <- sum((s-media_s)^4*f_s) #kurtosis convoluciones
coef_kur_s <- kurtosis_s/(var_s)^2

kurtosis_gama_s <- (6/alpha)+3

coef_kur_s
kurtosis_gama_s
```

#Percentiles

```{r}
percentiles <- c(0.25,0.50,0.75,0.95,0.99)
per_sim <- quantile(sim_i$sim,percentiles) #Percentiles de simulaciones
per_sim

#Percentiles de las convolusiones
#25
per25_s <- filter(mod_agregado,`F(s)`<0.25)
per25_s <- ifelse(dim(per25_s)[1]!=0,per25_s$s %>% max(),0)

#50
per50_s <- filter(mod_agregado,`F(s)`<0.50)
per50_s <- ifelse(dim(per50_s)[1]!=0,per50_s$s %>% max(),0)

#75
per75_s <- filter(mod_agregado,`F(s)`<0.75)
per75_s <- ifelse(dim(per75_s)[1]!=0,per75_s$s %>% max(),0)

#95
per95_s <- filter(mod_agregado,`F(s)`<0.95)
per95_s <- ifelse(dim(per95_s)[1]!=0,per95_s$s %>% max(),0)

#99
per99_s <- filter(mod_agregado,`F(s)`<0.99)
per99_s <- ifelse(dim(per99_s)[1]!=0,per99_s$s %>% max(),0)

per_s <- c(per25_s,per50_s,per75_s,per95_s,per99_s)
per_s #Percentiles de la convolución
```

## Pregunta 2

```{r}
set.seed(139380)

n_sim <- 10000
sim_serie <- NULL
sim_serie <- matrix(nrow=n_sim,ncol=2)
for(i in 1:(n_sim-1)){
sim_serie[1,1] <- rexp(1,lambda) #Tiempo 1
sim_serie[1,2] <- rexp(1,theta) #Monto 1

sim_serie[i+1,1] <- rexp(1,lambda) + sim_serie[i,1]

sim_serie[i+1,2] <- rexp(1,theta)
}


sim_serie <- data.frame(T_i=sim_serie[,1],
                        X_i=sim_serie[,2])

sim_serie <- sim_serie %>% mutate(S_t=cumsum(X_i))

ggplot(sim_serie, aes(x=T_i,y=X_i)) + geom_step() + coord_cartesian(xlim=c(0,100))

ggplot(sim_serie, aes(x=T_i,y=S_t)) + geom_step() + coord_cartesian(xlim=c(0,100),ylim=c(0,200000))
```

2.3

```{r}
t_vector <- length(sim_serie$X_i)
sop <- c(0:(t_vector-1))
 
real_X <- data.frame(soporte=c(0:100000),teorica=pexp(c(0:100000),theta))

#Percentiles
#media_per <-length(sop)*(.1) 
#var_per <- length(sop)*(.1)*(.9)
#sd_per <- sqrt(var_per)
#Int_conf_p <- c((-1.645)*sd_per+media_per+.5,(1.645)*sd_per+media_per+.5)
#Int_conf_p

media_per <- function(x){length(sop)*(x*1/t_vector)}
sd_per <- function(x){sqrt(length(sop)*(1/t_vector)*(1/(t_vector-1)))}
alpha <- qnorm(.99)
#se añaden los percentiles y los estadísticos de orden
sim_serie <- sim_serie %>% mutate(X_ord=sort(X_i),i=sop+.5
                                  ,ind_inf=floor(-alpha*sd_per(sop)+media_per(sop)+2)
                                  ,ind_sup=ceiling(alpha*sd_per(sop)+media_per(sop)+2)
                                  ,q=i/t_vector+0.00005
                                  ,inf=ifelse(ind_inf>0,X_ord[ind_inf],min(X_ord))
                                  ,sup=ifelse(ind_sup<t_vector,X_ord[ind_sup],max(X_ord)))

ggplot(sim_serie) + stat_ecdf(aes(X_i))+ geom_line(data=real_X,aes(x=soporte,y=teorica),col="red") + geom_line(aes(x=inf,y=q),col="blue") + geom_line(aes(x=sup,y=q),col="blue")
View(sim_serie)
```


